### ISSUE TITLE
'Recurse' with 'cy.request().then()' returns null

### ISSUE THREAD

**Issue by Maleckidd** [bahmutov/cypress-recurse#109]
Hi! In cypress 9.7.0 I used recurses with cy.request().then(), like in the example below. After Cypress update to 10.11.0, condition in recurse returns FALSE. I have notice that 'res' returns null in this case. When I remove .then() from cy.request(), recursion starts work normally, also works if cy.wrap(res) is added in .then()
 
`recurse(
   () =>
      cy.request({
       }).then((response) => {
          if(response.status === 200) cy.log(response.body.taskStatus)
      }), (res) => res.body.taskStatus === 'DONE',
   { delay: ... etc. }
)`

**Comment by bahmutov** [comment]
This is because Cypress v10 unexpectedly changed the return type of `cy.log` command from undefined (which continues with the previous subject) to `null` (which replaces whatever subject there was...) https://github.com/cypress-io/cypress/issues/23400
