### ISSUE TITLE
questions: correct implementation for reloading a page if a url does not transform to the target one

### ISSUE THREAD

**Issue by borecz** [bahmutov/cypress-recurse#22]
Hey @bahmutov this is a question not an issue:

I am bumping into an implementation problem with cypress-recurse. Please look at the current function:

`const submitPayment = () =>
  new Cypress.Promise(resolve => {
    let i = 0;
    recurse(
      () => {
        if (i++ > 0) {
          cy.reload();
        }
        CO.submitOrder(true);
        if (isStaging) handlePayment('Mastercard');
        return cy.url();
      },
      url => {
        cy.wrap(url)
          .should('include', '/checkout/success', {setTimeout: 20000})
          .then(() => resolve(true));
      },
      {
        log: true,
        limit: 5,
        timeout: 30000,
        delay: 1000,
      },
    );
  });`
  
basically the function should end when the url correctly contains `/checkout/success`, while if that is not the case, should repeat a few steps (reloading only in case of iterations after the first one) + some steps defined somewhere else and then go back to test the url.

This over-engineering is due to the fact that this url transition is very often buggy (only on cypress and not manually), because of 2 system transitioning in here, thus I would need a tentative, iterational  more resilient approach than just going straight to the next page (failing rate at 50%)

Would you please suggest a refactoring of this function? I believe we can bypass the Promise here and, anyway, the negative case keeps failing.

**Comment by bahmutov** [comment]
I don't understand what you are trying to do - and you are not using this `cypress-recurse` here but try to implement this yourself? Can you set up a small test that shows what you are trying to accomplish? Currently it is looking like you are trying to reload the page until the right thing happens, just like I show in the example here https://github.com/bahmutov/cypress-recurse#examples

**Comment by borecz** [comment]
Is it possible to return to the predicate function instead of `true` a Cypress.chainable<boolean> I guess in this way I would be able to first assert the url without losing the retriability/time-out and then if assertions passes to return true, or the passed assertion should directly be the truty value to end the recurse function.

`const submitPayment = () => {
    let i = 0;
    recurse(
      () => {
        if (i++ > 0) {
          cy.reload();
        }
        CO.submitOrder(true);
        if (isStaging) handlePayment('Mastercard');
        return cy.url();
      },
      url => 
        cy.wrap(url)
          .should('include', '/checkout/success', {setTimeout: 5000}),
      {
        log: true,
        limit: 10,
        timeout: 60000,
        delay: 1000,
      },
    )
};
`

**Comment by bahmutov** [comment]
Tip: you can use code blocks to format your code instead of long lines

```js
const submitPayment = () => {
    let i = 0;
    recurse(
      () => {
        if (i++ > 0) {
          cy.reload();
        }
        CO.submitOrder(true);
        if (isStaging) handlePayment('Mastercard');
        return cy.url();
      },
      url => 
        cy.wrap(url)
          .should('include', '/checkout/success', {setTimeout: 5000}),
      {
        log: true,
        limit: 10,
        timeout: 60000,
        delay: 1000,
      },
    )
```

Second, why have your own counter there? And the predicate - do not use Cypress commands there. You are returning `cy.url()` right? So the predicate should be simply `(s) => s.includes('/checkout/success')`

**Comment by borecz** [comment]
about the code blocks, right not sure why it did format this way :)

regarding the predicate also correct, I am already passing a string which won't mutate in there.

The reason of the counter is that, in the first place I do not want a reload to happen.

The scenario is:

go to checkout page, confirm a few checkbox then submit order, if the next page is order-success-page then finish, otherwise, reload the page and re-check those cheboxes.

There are cases where reloading in the middle of the loading page will bring user to success-page, some other times it will bring him back to checkout-page.

Very tricky here.

**Comment by bahmutov** [comment]
It is hard for me to say what is happening or what should happen. But I want to point out there is another option "post" that you could use https://github.com/bahmutov/cypress-recurse#post

**Comment by borecz** [comment]
here is the working solution I came out with following your advices @bahmutov, thank you!

`const submitPayment = () => {
  let first = true
    recurse(
      () => {
        return cy.get('body').then($body => {
          if($body.find('[data-testid="ospSummaryContainer"]').length <= 0 || first){
            CO.submitOrder(true);
            if (isStaging) handlePayment('Mastercard');
            cy.wait(3000)
            return cy.url();
          } else return true
        })
      },
      url => url.includes('/checkout/success') || url,
      { 
        post: ({limit}) => {
          cy.log(`current limit is ${limit}`)
          if(limit > 1){
            first = false
            cy.reload()
          }
        },
        log: true,
        limit: 10,
        timeout: 60000,
        delay: 1000,
      },
    )
}`
