### ISSUE TITLE
Recurse till element contains text

### ISSUE THREAD

**Issue by Lstylezz** [bahmutov/cypress-recurse#26]
Hey @bahmutov i have a question for the correct usage of the cypress-recurse.
I want to click a button till my element contains a specific text. 
I tried it like that:

`    recurse(
      () => cy.get('[data-test="' + table + '"]').get('td'),
      ($tableCell) => $tableCell.contains(nodeText),
      {
        post() {
          cy.get('.mat-paginator-navigation-next').click();
        }
      }
    );
    `
    
  but it seems that $tableCell never contains the specific text.
When i'm searching for an element on the first page and i search like that:
`cy.get('[data-test="' + table + '"]').get('td').contains(nodeText);`
I'll get my element but when i do it with the recurse-function i dont.

Do you have any advise for the correct usage in this case?

**Comment by bahmutov** [comment]
Please set up a reproducible example like a tiny repo with the test and the HTML page to run it against.

**Comment by Lstylezz** [comment]
I'm sorry I am pretty new to all of this and don't know how to quickly set up a repo with all its dependencies for it to work.

Basically what I have is a page with a table like that:
[https://stackblitz.com/angular/lmggjpglldkq?file=src%2Fapp%2Ftable-http-example.html](url)

in my Test I want to click the "next"-button of the pagination till the table displays an cell with the passed text.

For example, in the given table in the stackblitz-example I want to find the cell with the text "23094". 
It wouldn't find it on the first page, so it would have to click on the "next"-button of the pagination, then on the second page it would find the cell and not click the "next"-button any time again.

So in my function

```
function findElement(table: string, nodeText: string) {
  recurse( 
	  () => cy.get('[data-test="' + table + '"]').get('td'),
	  ($tableCell) => $tableCell.contains(nodeText), 
	  { 
		  post() {
			  cy.get('.mat-paginator-navigation-next').click();
		  }
	  }
   );
}
```
i expect the function would do the click one time and then $tableCell.contains(nodeText) should be true so the recurse stops. But it doesn't, $tableCell never contains the text.

When I do it manually: 
```
 cy.get('.mat-paginator-navigation-next').click();
 cy.get('[data-test="' + table + '"]').get('td').contains(nodeText);
```
it finds the element, so its 100% there.

**Comment by bahmutov** [comment]
Are you testing with the table from the stackblitz example? I just added a similar test in https://github.com/bahmutov/cypress-recurse/commit/ef836125d6c74564633b236a26cbbe60ae6910a9 to show `post`. You can always add `debugger` keyword inside the functions and check what it finds on the page
