### ISSUE TITLE
Handling Scenarios Where No Elements Are Found After Clicking on a DeckGL Canvas During Recursion

### ISSUE THREAD

**Issue by iamravisingh** [bahmutov/cypress-recurse#326]
Hi @bahmutov,

**Context**
I've been working on a Cypress test where I need to select multiple 3D points on a map rendered using the DeckGL library. After selecting these points, I want to verify that they appear in a side panel. The points are displayed as `hds-list-item` elements inside a container with the class `pointListContainer`.

However, I've encountered an issue: if no points are selected, the `hds-list-item` elements don't exist, and Cypress throws an error, causing the test to fail before the recursion can work.

**Issue**
Using `cy.get('[class="pointListContainer"] hds-list-item').its("length")` inside the cypress-recurse loop works well when points are selected. But if no points are selected, this command fails because Cypress can't find the `hds-list-item` elements, and the test stops running.

**Current Solution**
To handle this scenario, I modified the recursion logic first to check whether the `hds-list-item` elements exist and only then count their length. Here's what the updated code looks like:

```javascript
       const points = [
        { x: 400, y: 600 },
        { x: 450, y: 650 },
        { x: 500, y: 700 },
        { x: 600, y: 800 },
       ];

                // Iterate over all points
                points.forEach((point) => {
                    cy.get("@deck").click(point.x, point.y);
                    cy.recurse(
                        () => {
                            // Check if the pointListContainer has any items
                            return cy.get('[class="pointListContainer"]').then(($container) => {
                                // If hds-list-item exists, return the length, otherwise return 0
                                const items = $container.find("hds-list-item");
                                return items.length > 0 ? items.length : 0;
                            });
                        },
                        (length) => {
                            cy.log(`Found ${length} points selected`);
                            return length > 0; // Continue recursion until at least one point is selected
                        },
                        {
                            ...recurseDefaultConfig,
                            delay: 1000,
                            timeout: 15000,
                        }
                    );
                });
``` 

Above approach ensures that the recursion continues even when no points are initially selected, without causing the test to fail prematurely. It works well, but I wanted to share this use case and see if there's a more elegant or built-in way to handle such scenarios using `cypress-recurse`. Ideally, there shouldn't be a chance to use recurse for this issue. However, the way I was facing a problem, where `onclick` points are highlighted and working locally and the same is failing in CI is quite weird and I am very interested in solving this. 

Would it make sense to include a built-in option or pattern in `cypress-recurse` for handling cases where elements might not exist? Or perhaps there's already a recommended practice that I'm missing?

Looking forward to hearing your thoughts and suggestions!

**Comment by iamravisingh** [comment]
To add more over this discussion, extending with some screenshots 

This image is my local test run and it shows a point click and some details on the side panel. However, the same test case in CI is crying, those clicked red highlighted are not visible. My take was, that if this was flaky issue, then with recursion this might have resolve. 

![image](https://github.com/user-attachments/assets/9b416a2c-52c2-4f42-bed6-a2194a68025f)

**Comment by bahmutov** [comment]
Sometimes not finding elements and doing something else instead is not the focus of this plugin, use https://github.com/bahmutov/cypress-if (or implement a similar technique) for that
