### ISSUE TITLE
Interdependence of timeout and limit when log is set to false

### ISSUE THREAD

**Issue by SriSivaBatchu** [bahmutov/cypress-recurse#40]
Hi Gleb,

I think there is some Interdependence of timeout and limit when log is set to false.
Lets take an example of download file, it takes 100 sec's to download. So as per time requirement I'm passing timeout as 100000.
`recurse(
()=> cy.task('event', 'args'),
() => condition,
  {
    timeout: 10000,
    log: false
    }
)`
But the default value of limit is 30. So before completion of 100 sec's, the limit is reaching to 30.
**This is observed when log is set to false**
One more thing could you please inform how to pass log: false for a task. So that the task w

**Comment by bahmutov** [comment]
- I am open to a fix
- it is missing a reproducible example

**Comment by bahmutov** [comment]
Can you try this again? I just fixed a problem in timing, so it might have fixed your issue too

**Comment by bahmutov** [comment]
assuming this was fixed
