### ISSUE TITLE
Timeout does not re-initialize upon repeated calls in the same test

### ISSUE THREAD

**Issue by j1000** [bahmutov/cypress-recurse#45]
Sorry I don't have a reproducible example (yet), but I think you'll find this easy to reproduce.

1. Call recurse() for something that takes a while
2. Repeat the recurse() later in the test for the same activity

Expected: timeout should start back at the original value
Actual: timeout continues where it left off

We're using your excellent plugin for several email tests, including one for multi-factor authentication (with ethereal.email), and for the time being we have a long journey test where the user enrolls, waits for the authentication code email, signs out/in, waits for the authentication code email, then unenrolls and waits for the authentication code once more. We're using a 3rd party SMTP service which does not immediately send. So it becomes noticeable when the timeout does not reset :) It's easy to work around this by increasing the timeout. (And I may try to figure out a way to break it up by seeding the data.)

Here's an illustration of the issue. Notice how it the Time Remaining log entries do not continue from the initial value of 300000. This is because it's late in the test, when a lot of waiting has already happened with previous calls.

![image](https://user-images.githubusercontent.com/10520969/140836104-a8f579fc-1609-418d-843a-75b344d6dfaa.png)

**Comment by bahmutov** [comment]
Yeah, it seems to be wrong
```js
describe('timeout option', () => {
  it('sets custom timeout', () => {
    recurse(getTo(10), (x) => x === 10, {
      timeout: 15000,
      delay: 1000,
    })
    cy.log('**second**')
    recurse(getTo(10), (x) => x === 10, {
      timeout: 15000,
      delay: 1000,
    })
  })
})
```

The second `recurse` shows the correct `timeout` on the first attempt, and then has it wrong

<img width="433" alt="Screen Shot 2021-11-21 at 07 21 59" src="https://user-images.githubusercontent.com/2212006/142761577-e3075431-0141-4b2c-b413-9bcbb24d4c31.png">
