### ISSUE TITLE
Custom Timeout Message

### ISSUE THREAD

**Issue by troynguyenh** [bahmutov/cypress-recurse#48]
Would it be possible to set custom messages when timed out rather than 'recursion limit reached'?

Thanks :)

**Comment by bahmutov** [comment]
I think you could open a pull request to add this feature

**Comment by troynguyenh** [comment]
Sweet, will get to it

**Comment by bahmutov** [comment]
Done in https://github.com/bahmutov/cypress-recurse/pull/49
