### ISSUE TITLE
For log:true "NICE!" is getting logged when control exits recursion

### ISSUE THREAD

**Issue by royarunendu** [bahmutov/cypress-recurse#60]
cypress-recurse : 1.13.1
if **log: true** is set in options then "NICE!" gets logged in the test runner window as well.  
In the actual use case is there any use of it?

**Comment by bahmutov** [comment]
no, but it is nice to know when the recursion successfully finishes

**Comment by iMarv** [comment]
"Nice! The recursion finished successfully!" ?
