### ISSUE TITLE
Is it possible to log response from cy.request() when recursion ends?

### ISSUE THREAD

**Issue by romankhomitskyi** [bahmutov/cypress-recurse#66]
I was wondering if it's possible to log response from cy.request() when recursion ends?

Like
 {
  error: response.body
}

**Comment by bahmutov** [comment]
can you provide the full example of what you are trying to do?

**Comment by romankhomitskyi** [comment]
Instead of error max time limit is reached
<img width="451" alt="Screenshot 2022-03-23 at 21 01 19" src="https://user-images.githubusercontent.com/57874507/159775966-d9763bb2-b370-437d-96d5-8d5482a58755.png">

I would like to have Cypress error
![image](https://user-images.githubusercontent.com/57874507/159776341-776295f3-1fa6-4713-8d26-2e6c3dacc61f.png)

**Comment by bahmutov** [comment]
Is the error thrown from the predicate function?

**Comment by romankhomitskyi** [comment]
```
const apiRequest = (): Cypress.Chainable<Cypress.Response<any>> => {
		return cy.request({ followRedirect: false, failOnStatusCode: false, ...options });
	};v

const shouldBeAuthorized = (response): boolean => response.status !== 401;

return recurse(apiRequest, shouldBeAuthorized, { post: getNewToken, log: true, limit: 5, delay: 1000 }).then(
		response => {
			if (clientErrors.includes(response.status) || serverErrors.includes(response.status)) {
				throw new Error(
					`Status code ${response.status} Request Headers ${JSON.stringify(
						response.requestHeaders
					)}  Response Body ${JSON.stringify(response.body)} `
				);
			}
			return response;
		}
	);
```

Here is my use case
Instead of my custom Error and  error max time limit is reached I would like to get Cypress Error  when the last iteration is failed
Is it possibe?
