### ISSUE TITLE
Can't combine with cypress-plugin-snapshots

### ISSUE THREAD

**Issue by DamienCassou** [bahmutov/cypress-recurse#67]
[cypress-plugin-snapshots](https://www.npmjs.com/package/cypress-plugin-snapshots) allows me to do visual comparison. Because I'm trying to check a line chart with an animation, I would like to make cypress-plugin-snaphost retry on failure:

```js
recurse(
	() => cy.get("#line-chart"),
	() => cy.get("l#ine-chart").toMatchImageSnapshot()
);
```

Unfortunately, this fails immediately instead of retrying:
![2022-01-26-112604](https://user-images.githubusercontent.com/217543/151146678-dabac151-97f3-4878-80ab-bcf016b8d346.png)

I've read many of your blog posts, including those mentioning [odiff](https://github.com/dmtrKovalenko/odiff) and [monalego](https://github.com/bahmutov/monalego/). I would happily use that if you believe cypress-plugin-snapshot isn't a good plugin. There just [isn't any odiff Cypress plugin](https://github.com/dmtrKovalenko/odiff/issues/62) (yet?).

**Comment by bahmutov** [comment]
Well, if they implemented a utility method that would compare images without failing, that could work. But since they throw an error and fail the test, this plugin cannot do much
