### ISSUE TITLE
Recursion fails after last successful iteration

### ISSUE THREAD

**Issue by marksgitacc** [bahmutov/cypress-recurse#75]
I tried to use recurse() command to navigate from subpages back to main page. There are multiple levels of subpages and each has "back" button available, but the main page does not contain this element.

Code used:
`
recurse(
      () => cy.get("[data-test-id=btn-go-back]").should(() => {}),
      ($button) => $button.length === 0,
      {
        limit: 5,
        post() {
          cy.get("[data-test-id=btn-go-back]").click();
        },
      }
    );
`

![image](https://user-images.githubusercontent.com/80096873/156198836-a54778cb-9e46-421e-aa62-fe8f3bd982ff.png)
It seems once last iteration navigated to main page without back button, yielding result caused assertion error.
Changing temporarily this: `return cy.wrap(x, { log: false })`
to this: `return cy.wrap(x, { log: false }).should(()=>{})` or this: `return` helped in my case

**Comment by bahmutov** [comment]
Interesting, it ends on a non-existent element, let me see ...

**Comment by marksgitacc** [comment]
thank you for the fix
